CREATE TABLE IF NOT EXISTS validation (
	up VARCHAR(42),
	message VARCHAR(69),
	validation_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS last_block (
	block BIGINT,
	update_time DATETIME DEFAULT CURRENT_TIMESTAMP
);
